import "./globals.css";
import Navbar from "./Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <div style={{ position: "fixed", top: 0, left: 0, width: "100vw", zIndex: 100 }}>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
