import "./globals.css";
import Navbar from "./Navbar";
import ClientLoader from "../../components/ClientLoader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{
        marginTop: 0,
        marginRight: 0,
        marginBottom: 0,
        marginLeft: 0,
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: 0
      }}>
        <ClientLoader>
          <div style={{ position: "fixed", top: 0, left: 0, width: "100vw", zIndex: 100 }}>
            <Navbar />
          </div>
          {children}
        </ClientLoader>
      </body>
    </html>
  );
}
